import SEO from "@/app/components/SEO";
import { seoConfig } from "@/lib/seo-config";

export default function PrivacyPolicy() {
  return (
    <>
      <SEO 
        title={seoConfig.privacyPolicy.title}
        description={seoConfig.privacyPolicy.description}
        url={seoConfig.privacyPolicy.url}
      />
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">PRIVACY POLICY</h1>
      <p className="text-sm text-gray-600 mb-8">Last updated: November 17, 2025</p>

      <div className="prose max-w-none">
        <p className="mb-6">
          This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.
        </p>
        <p className="mb-8">
          We use your Personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">INTERPRETATION AND DEFINITIONS</h2>
          
          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-2">INTERPRETATION</h3>
            <p>
              The words with initial capital letters have meanings defined under the following conditions. These definitions shall have the same meaning whether they appear in singular or plural.
            </p>
          </div>

          <div>
            <h3 className="text-xl font-semibold mb-4">DEFINITIONS</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            
            <dl className="space-y-4">
              <div>
                <dt className="font-semibold">Account</dt>
                <dd className="ml-4 mb-2">means a unique account created for you to access our Service or parts of our Service.</dd>
              </div>

              <div>
                <dt className="font-semibold">Affiliate</dt>
                <dd className="ml-4 mb-2">
                  means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or managing authority.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Company</dt>
                <dd className="ml-4 mb-2">
                  (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to DSL Limo Service.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Cookies</dt>
                <dd className="ml-4 mb-2">
                  are small files placed on your device by a website, containing details of your browsing history among other uses.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Country</dt>
                <dd className="ml-4 mb-2">refers to: United States</dd>
              </div>

              <div>
                <dt className="font-semibold">Device</dt>
                <dd className="ml-4 mb-2">
                  means any device that can access the Service, such as a computer, cell phone, or tablet.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Personal Data</dt>
                <dd className="ml-4 mb-2">
                  is any information that relates to an identified or identifiable individual.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Service</dt>
                <dd className="ml-4 mb-2">refers to the Website.</dd>
              </div>

              <div>
                <dt className="font-semibold">Service Provider</dt>
                <dd className="ml-4 mb-2">
                  means any natural or legal person who processes the data on behalf of the Company.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Usage Data</dt>
                <dd className="ml-4 mb-2">
                  refers to data collected automatically, generated by the use of the Service or the Service infrastructure.
                </dd>
              </div>

              <div>
                <dt className="font-semibold">Website</dt>
                <dd className="ml-4 mb-2">
                  refers to DSL Limo Service, accessible from https://dsllimoservice.com/
                </dd>
              </div>

              <div>
                <dt className="font-semibold">You</dt>
                <dd className="ml-4 mb-2">
                  means the individual using the Service, or the company or other legal entity on whose behalf the individual is using the Service.
                </dd>
              </div>
            </dl>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">COLLECTING AND USING YOUR PERSONAL DATA</h2>
          
          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">SMS OPT-IN STATEMENT</h3>
            <p className="mb-4">
              SMS opt-in or phone numbers for the purpose of SMS are not shared with any third-party or affiliate companies for marketing purposes.
            </p>

            <div className="ml-4">
              <h4 className="text-lg font-semibold mb-2">1. SMS Terms &amp; Conditions</h4>
              
              <div className="space-y-4">
                <div>
                  <h5 className="font-semibold">SMS Consent Communication:</h5>
                  <p>Phone numbers obtained during the SMS consent process will not be shared with third parties for marketing.</p>
                </div>

                <div>
                  <h5 className="font-semibold">Types of SMS Communications:</h5>
                  <p>
                    If you consent to receive SMS messages from DSL Limo Service, you may receive messages related to:
                  </p>
                  <ul className="list-disc ml-6 mt-2">
                    <li>Reservation updates</li>
                    <li>Services updates</li>
                    <li>Customer care messages</li>
                  </ul>
                </div>

                <div>
                  <h5 className="font-semibold">Message Frequency:</h5>
                  <p>You may receive 3–5 SMS messages per week, depending on service activity.</p>
                </div>

                <div>
                  <h5 className="font-semibold">SMS Fees:</h5>
                  <p>Standard message and data rates may apply based on your mobile carrier.</p>
                </div>

                {/* <div>
                  <h5 className="font-semibold">Opt-In Method:</h5>
                  <p>You may opt in by submitting an online form.</p>
                </div> */}

                <div>
                  <h5 className="font-semibold">Opt-Out Method:</h5>
                  <p>Reply &quot;STOP&quot; to any SMS, or contact us directly.</p>
                </div>

                <div>
                  <h5 className="font-semibold">Help:</h5>
          
                </div>

                <div>
                  <h5 className="font-semibold">Standard Disclosures:</h5>
                  <ul className="list-disc ml-6">
                    <li>Message and data rates may apply</li>
                    <li>Text &quot;STOP&quot; to unsubscribe</li>
                    <li>Reply &quot;HELP&quot; or contact us at +1 800 679 3415</li>
                    <li>Message frequency may vary</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">TYPES OF DATA COLLECTED</h3>
            
            <div className="mb-4">
              <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
              <p className="mb-2">We may collect the following types of personally identifiable information:</p>
              <ul className="list-disc ml-6">
                <li>Email address</li>
                <li>First and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal Code, City</li>
              </ul>
            </div>

            <div>
              <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
              <p className="mb-2">Automatically collected information may include:</p>
              <ul className="list-disc ml-6">
                <li>IP address</li>
                <li>Browser type and version</li>
                <li>Pages visited on our Service</li>
                <li>Time and date of visit</li>
                <li>Time spent on pages</li>
                <li>Device identifiers</li>
                <li>Mobile device and operating system details</li>
              </ul>
            </div>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">TRACKING TECHNOLOGIES AND COOKIES</h3>
            <p className="mb-4">
              We use Cookies, beacons, tags, and scripts for monitoring and improving our Service.
            </p>
            
            <div className="mb-4">
              <h4 className="text-lg font-semibold mb-2">Types include:</h4>
              <ul className="list-disc ml-6">
                <li>Session Cookies (temporary)</li>
                <li>Persistent Cookies (remain after closing browser)</li>
              </ul>
            </div>

            <div>
              <h4 className="text-lg font-semibold mb-2">We use cookies for:</h4>
              <ul className="list-disc ml-6">
                <li>Essential website features</li>
                <li>Cookies policy acceptance</li>
                <li>Saving user preferences</li>
              </ul>
            </div>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">USE OF YOUR PERSONAL DATA</h3>
            <p className="mb-4">
              The Company may use Personal Data for purposes such as:
            </p>
            <ul className="list-disc ml-6">
              <li>Providing and maintaining our Service</li>
              <li>Managing your Account</li>
              <li>Performance of a contract</li>
              <li>Communicating via email, phone, SMS</li>
              <li>Sending news, offers, and updates</li>
              <li>Processing requests</li>
              <li>Business transfers</li>
              <li>Analytics and service improvement</li>
            </ul>
            <p className="mt-4">
              We may share data with Service Providers, Affiliates, business partners, or with your consent.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">RETENTION OF YOUR PERSONAL DATA</h3>
            <p>
              We retain Personal Data only as long as necessary for the purposes outlined in this policy.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">TRANSFER OF YOUR PERSONAL DATA</h3>
            <p>
              Your data may be transferred to computers located outside your jurisdiction. We ensure all reasonable measures to secure these transfers.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">DELETE YOUR PERSONAL DATA</h3>
            <p>
              You may request deletion of your data at any time. Some data may be retained as legally required.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">DISCLOSURE OF PERSONAL DATA</h3>
            
            <div className="mb-4">
              <h4 className="text-lg font-semibold mb-2">Business Transactions</h4>
              <p>Data may be transferred during mergers or acquisitions.</p>
            </div>

            <div className="mb-4">
              <h4 className="text-lg font-semibold mb-2">Law Enforcement</h4>
              <p>We may disclose Personal Data if required by law.</p>
            </div>

            <div>
              <h4 className="text-lg font-semibold mb-2">Other Legal Requirements</h4>
              <p>We may disclose data to:</p>
              <ul className="list-disc ml-6">
                <li>Comply with legal obligations</li>
                <li>Protect rights or property</li>
                <li>Prevent wrongdoing</li>
                <li>Protect user safety</li>
                <li>Defend against legal liability</li>
              </ul>
            </div>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">SECURITY OF YOUR PERSONAL DATA</h3>
            <p>
              We use commercially acceptable methods to protect your data, but no method is 100% secure.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">CHILDREN&apos;S PRIVACY</h3>
            <p>
              We do not knowingly collect data from individuals under 13.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">LINKS TO OTHER WEBSITES</h3>
            <p>
              We are not responsible for third-party website content or privacy policies.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-4">CHANGES TO THIS PRIVACY POLICY</h3>
            <p>
              We may update this Policy periodically and will notify you of significant changes.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">PAYMENT</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>If you cancel a ride, 5% of your payment will be deducted to cover transaction fees.</li>
            <li>If you cancel the ride after 8 hours, 15% will be deducted from your payment.</li>
            <li>Additional costs such as tolls or detours will be billed separately.</li>
            <li>Tips are voluntary.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h3 className="text-xl font-semibold mb-4">CONTACT US</h3>
          <p className="mb-4">
            If you have questions about this Privacy Policy, you may contact us:
          </p>
          <ul className="list-disc ml-6">
            <li>By email: info@dsllimoservice.com</li>
            <li>By website: https://dsllimoservice.com/contact-us/</li>
            <li>By phone number: +1 800 679 3415</li>
          </ul>
        </section>
      </div>
    </div>
    </>
  );
}